services:
  vr-escape-room:
    build: .
    ports:
      - "8443:8443"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    volumes:
      - ./certs:/app/certs:ro
    networks:
      - vr-network

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.prod.conf:/etc/nginx/nginx.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - vr-escape-room
    restart: unless-stopped
    networks:
      - vr-network

networks:
  vr-network:
    driver: bridge
